image: node:8
pipelines:
  branches:
    develop:
      - step:
          script:
          - apt-get update && apt-get install -y rsync
          - npm i -g gulp bower
          - npm i
          - bower --allow-root instal
          - gulp prod
            # Change <remote host IP> to real IP
            # You can use current abweb droplet for test sites - 37.139.27.120
          - rsync -rahvz --delete-after $(pwd)/dist/ root@<remote host IP>:/home/admin/web/$SITE/public_html
